// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_5rGrxfhPPsaZ3WaFwN_E9LmWKgMtC0Y',
    appId: '1:73049652113:web:c3f2f7ba63b2b341443830',
    messagingSenderId: '73049652113',
    projectId: 'streetmatt-d4392',
    authDomain: 'streetmatt-d4392.firebaseapp.com',
    storageBucket: 'streetmatt-d4392.appspot.com',
    measurementId: 'G-LMBX5Q52RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFBZ54p5XR8D3GX7FURH6kzqA1x31icHQ',
    appId: '1:73049652113:android:9181020857d50941443830',
    messagingSenderId: '73049652113',
    projectId: 'streetmatt-d4392',
    storageBucket: 'streetmatt-d4392.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa1yk0iR1a3P_Ti6iIvP7Yo1-2XMAK-9k',
    appId: '1:73049652113:ios:0c6263d43e5fb813443830',
    messagingSenderId: '73049652113',
    projectId: 'streetmatt-d4392',
    storageBucket: 'streetmatt-d4392.appspot.com',
    iosBundleId: 'com.example.connecta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa1yk0iR1a3P_Ti6iIvP7Yo1-2XMAK-9k',
    appId: '1:73049652113:ios:bfe562c022a2f4de443830',
    messagingSenderId: '73049652113',
    projectId: 'streetmatt-d4392',
    storageBucket: 'streetmatt-d4392.appspot.com',
    iosBundleId: 'com.example.connecta.RunnerTests',
  );
}
